version: "3"

services:
  cadvisor:
    restart: always
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      # Default location
      # - "/var/lib/docker/:/var/lib/docker:ro"
      # Snap location
      - "/var/snap/docker/current:/var/lib/docker:ro"
    expose:
      - "8080"
    ports:
      - 8085:8080

  prometheus:
    restart: always
    depends_on:
    image: prom/prometheus:v2.14.0
    container_name: prometheus
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  exporter-1:
    image: dazwilkin/home-exporter:bdbd1e40faf8dc3a98c65e1412c122a33e5e0a3c
    container_name: exporter-1
    command:
    - "--device=192.168.86.24:8008"
    - "--endpoint=:9999"
    expose:
      - "9999"
    ports:
      - 9998:9999

  exporter-2:
    image: dazwilkin/home-exporter:bdbd1e40faf8dc3a98c65e1412c122a33e5e0a3c
    container_name: exporter-2
    command:
    - "--device=192.168.86.25:8008"
    - "--endpoint=:9999"
    expose:
      - "9999"
    ports:
      - 9997:9999